---

- name: "Copy 'content' entries"
  include: copy-inventory-entry.yml
  loop_control:
    loop_var: entry
  with_items:
  - "{{ content_entry.content }}"
  when:
  - content_entry.content is defined 

- name: "Copy 'content_dir' entries"
  vars:
    dir: "{{ content_entry.content_dir }}"
  include: copy-inventory-dir.yml
  when:
  - content_entry.content_dir is defined 
