---

openshift_cluster_content:
- object: projectrequest
  content:
  - name: "coolstore-micro-pipeline"
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/master/files/projectrequest/template.yml"
    params: "../templates/projectrequest/pipeline.params"
    template_action: create
 # - name: "coolstore-mono"
 #   template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/master/files/projectrequest/template.yml"
 #   params: "../templates/projectrequest/mono.params"
 #   template_action: create
  - name: "coolstore-micro-dev"
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/master/files/projectrequest/template.yml"
    params: "../templates/projectrequest/dev.params"
    template_action: create
  - name: "infographic-micro-demo"
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/master/files/projectrequest/template.yml"
    params: "../templates/projectrequest/demo.params"
    template_action: create
- object: rolebindings
  content:
  - name: "coolstore-micro-pipeline-rolebindings"
    file: "../templates/projectrequest/rolebindings.yml"
    file_action: apply
    namespace: coolstore-micro-pipeline
#  - name: "coolstore-mono-rolebindings"
#    file: "../templates/projectrequest/rolebindings.yml"
#    file_action: apply
#    namespace: coolstore-mono
  - name: "coolstore-micro-dev-rolebindings"
    file: "../templates/projectrequest/rolebindings.yml"
    file_action: apply
    namespace: coolstore-micro-dev
  - name: "coolstore-micro-demo-rolebindings"
    file: "../templates/projectrequest/rolebindings.yml"
    file_action: apply
    namespace: coolstore-micro-demo
- object: demo
  content:
  - name: coolstore-micro-dev
    template: "https://raw.githubusercontent.com/mono2micro/coolstore-micro/1.1.x/openshift/coolstore-template.yaml"
    params: "../templates/emptyparams"
    namespace: "coolstore-micro-dev"
- object: demo
  content:
  - name: coolstore-micro-demo
    template: "https://raw.githubusercontent.com/mono2micro/coolstore-micro/1.1.x/openshift/coolstore-template.yaml"
    params: "../templates/emptyparams"
    namespace: "coolstore-micro-demo"
#- object: builds
#  content:
#  - name: "coolstore-micro-web-ui-pipeline"
#    template: "../templates/build/template-pipeline.yml"
#    params: "../templates/build/pipeline.params"
#    namespace: "coolstore-micro-pipeline"
#  - name: "coolstore-micro-web-ui-build"
#    template: "../templates/build/template-web-ui-build.yml"
#    params: "../templates/build/web-ui-build.params"
#    namespace: "coolstore-micro-pipeline"
#  - name: "coolstore-micro-web-ui-2-pipeline"
#    template: "../templates/build/template-pipeline.yml"
#    params: "../templates/build/pipeline-web-ui-2.params"
#    namespace: "coolstore-micro-pipeline"
#  - name: "coolstore-micro-web-ui-2-build"
#    template: "../templates/build/template-web-ui-build.yml"
#    params: "../templates/build/web-ui-2-build.params"
#    namespace: "coolstore-micro-pipeline"
#- object: deployments
#  content:
#  - name: "coolstore-micro-web-ui-dev"
#    template: "../templates/deploy/template.yml"
#    params: "../templates/deploy/dev-web-ui.params"
#    namespace: "coolstore-micro-dev"
#  - name: "coolstore-micro-web-ui-demo"
#    template: "../templates/deploy/template.yml"
#    params: "../templates/deploy/demo-web-ui.params"
#    namespace: "coolstore-micro-demo"
#  - name: "coolstore-micro-web-ui-2-dev"
#    template: "../templates/deploy/template-web-ui-2.yml"
#    params: "../templates/deploy/dev-web-ui-2.params"
#    namespace: "coolstore-micro-dev"
#  - name: "coolstore-micro-web-ui-2-demo"
#    template: "../templates/deploy/template.yml"
#    params: "../templates/deploy/demo-web-ui-2.params"
#    namespace: "coolstore-micro-demo"
